name: Run main.py every 2 minutes

on:
  schedule:
    - cron: '*/4 * * * *'  # At every 2nd minute of every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade rbiparser


      - name: Execute Python script
        run: |
          echo "Checking current directory contents:"
          ls -al

          echo "Running rbiparser download -d "./xls":"
          rbiparser download -d "./xls"

